### ISSUE TITLE
Removing a class attribute

### ISSUE THREAD

**Issue by MikeiLL** [Rosuav/shed#1]
If I've added a class:

```
set_content("#info", "Some important info.").className = "important";
```

Is there a recommended was to remove it? Is it just:

```
set_content("#info", "Some unimportant info.").className = undefined;
```

**Comment by Rosuav** [comment]
This is standard DOM maipulation - set_content just returns the element itself. So you'd unset it the same way you would unset that attribute, usually by setting it to some default. With CSS classes, an empty string will mean no classes.

**Comment by MikeiLL** [comment]
Thank you. I can create another issue for this:

How to define a class attribute:

```
DIV({class: "useful-class"},"Information"),
```

Doesn't do it...

**Comment by Rosuav** [comment]
That's because the HTML "class" attribute is the DOM "className" attribute.

**Comment by Rosuav** [comment]
Unfortunately there's no solution to that one, and you'll come across it in everything that works with both HTML and DOM elements.

**Comment by MikeiLL** [comment]
Perfect. That had been my second go-to, but it appeared not to work at first. Are you leaving this issue opened for a reason? Would it make sense for me to close it?

**Comment by Rosuav** [comment]
Only because I didn't think to close it :)
